# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knn_dist <- function(dist_x, k) {
    .Call('_clustertree_knn_dist', PACKAGE = 'clustertree', dist_x, k)
}

knn_dist2 <- function(dist_x, k) {
    .Call('_clustertree_knn_dist2', PACKAGE = 'clustertree', dist_x, k)
}

getMergeIndices <- function(merge, m_i) {
    .Call('_clustertree_getMergeIndices', PACKAGE = 'clustertree', merge, m_i)
}

FOSC_int <- function(merge, f_1, f_2) {
    .Call('_clustertree_FOSC_int', PACKAGE = 'clustertree', merge, f_1, f_2)
}

normalizeIndices <- function(mst) {
    .Call('_clustertree_normalizeIndices', PACKAGE = 'clustertree', mst)
}

mstToCC <- function(mst, dist) {
    .Call('_clustertree_mstToCC', PACKAGE = 'clustertree', mst, dist)
}

mstToHclust <- function(mst_, dist) {
    .Call('_clustertree_mstToHclust', PACKAGE = 'clustertree', mst_, dist)
}

hclustMergeOrder <- function(mst, o) {
    .Call('_clustertree_hclustMergeOrder', PACKAGE = 'clustertree', mst, o)
}

ClusterTree_int <- function(x, k, alpha = 1.0, bucketSize = 15L, splitRule = 5L) {
    .Call('_clustertree_ClusterTree_int', PACKAGE = 'clustertree', x, k, alpha, bucketSize, splitRule)
}

primsRSL <- function(r, r_k, n, alpha, type) {
    .Call('_clustertree_primsRSL', PACKAGE = 'clustertree', r, r_k, n, alpha, type)
}

naive_clustertree <- function(dist_x, r_k, k, alpha, type = 0L) {
    .Call('_clustertree_naive_clustertree', PACKAGE = 'clustertree', dist_x, r_k, k, alpha, type)
}

testTrees <- function(x, k, bucketSize = 15L) {
    invisible(.Call('_clustertree_testTrees', PACKAGE = 'clustertree', x, k, bucketSize))
}

testClusterTree <- function(x, k, bucketSize = 15L, alpha = 1.0) {
    .Call('_clustertree_testClusterTree', PACKAGE = 'clustertree', x, k, bucketSize, alpha)
}

testKNN <- function(x, k, bucketSize = 15L, metric_choice = 0L) {
    .Call('_clustertree_testKNN', PACKAGE = 'clustertree', x, k, bucketSize, metric_choice)
}

testKNN_ref <- function(qx, rx, k, bucketSize = 15L, metric_choice = 0L) {
    .Call('_clustertree_testKNN_ref', PACKAGE = 'clustertree', qx, rx, k, bucketSize, metric_choice)
}

testMST <- function(x, bucketSize = 15L) {
    .Call('_clustertree_testMST', PACKAGE = 'clustertree', x, bucketSize)
}

kd_knn <- function(query_x, tree_ptr, k, priority) {
    .Call('_clustertree_kd_knn', PACKAGE = 'clustertree', query_x, tree_ptr, k, priority)
}

kdtree <- function(x, bkt_size) {
    .Call('_clustertree_kdtree', PACKAGE = 'clustertree', x, bkt_size)
}

kNN_int <- function(x, k, type, bucketSize, splitRule, approx, r_x) {
    .Call('_clustertree_kNN_int', PACKAGE = 'clustertree', x, k, type, bucketSize, splitRule, approx, r_x)
}

mergeHeight <- function(hcl) {
    .Call('_clustertree_mergeHeight', PACKAGE = 'clustertree', hcl)
}

kruskalsMST <- function(dist_x) {
    .Call('_clustertree_kruskalsMST', PACKAGE = 'clustertree', dist_x)
}

primsMST <- function(dist_x) {
    .Call('_clustertree_primsMST', PACKAGE = 'clustertree', dist_x)
}

cut_simplified_hclust <- function(hcl, cl_in, big_n) {
    .Call('_clustertree_cut_simplified_hclust', PACKAGE = 'clustertree', hcl, cl_in, big_n)
}

simplified_hclust <- function(hcl, min_sz) {
    .Call('_clustertree_simplified_hclust', PACKAGE = 'clustertree', hcl, min_sz)
}

reconnectComponents <- function(merge, height, h2) {
    .Call('_clustertree_reconnectComponents', PACKAGE = 'clustertree', merge, height, h2)
}

timesTwo <- function(x) {
    .Call('_clustertree_timesTwo', PACKAGE = 'clustertree', x)
}

test1 <- function(x) {
    .Call('_clustertree_test1', PACKAGE = 'clustertree', x)
}

test2 <- function(x) {
    .Call('_clustertree_test2', PACKAGE = 'clustertree', x)
}

vol_nSphere <- function(n, R = 1) {
    .Call('_clustertree_vol_nSphere', PACKAGE = 'clustertree', n, R)
}

