# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kruskalsMST <- function(dist_x) {
    .Call('clustertree_kruskalsMST', PACKAGE = 'clustertree', dist_x)
}

primsMST <- function(dist_x) {
    .Call('clustertree_primsMST', PACKAGE = 'clustertree', dist_x)
}

primsRSL <- function(r, r_k, n, alpha, type) {
    .Call('clustertree_primsRSL', PACKAGE = 'clustertree', r, r_k, n, alpha, type)
}

mstToHclust <- function(mst, n) {
    .Call('clustertree_mstToHclust', PACKAGE = 'clustertree', mst, n)
}

clusterTree <- function(dist_x, r_k, k, alpha = 1.414213562373095, type = 0L, knn_indices = integer()) {
    .Call('clustertree_clusterTree', PACKAGE = 'clustertree', dist_x, r_k, k, alpha, type, knn_indices)
}

naive_clustertree <- function(x, r_k, alpha = 1.414213562373095, type = 0L) {
    .Call('clustertree_naive_clustertree', PACKAGE = 'clustertree', x, r_k, alpha, type)
}

dt_knn <- function(q_x, k, r_x = matrix(), bkt_size = 30L, prune = FALSE) {
    .Call('clustertree_dt_knn', PACKAGE = 'clustertree', q_x, k, r_x, bkt_size, prune)
}

kd_knn <- function(query_x, tree_ptr, k) {
    .Call('clustertree_kd_knn', PACKAGE = 'clustertree', query_x, tree_ptr, k)
}

kdtree <- function(x, bkt_size) {
    .Call('clustertree_kdtree', PACKAGE = 'clustertree', x, bkt_size)
}

kNN_int <- function(data, k, type, bucketSize, splitRule, approx) {
    .Call('clustertree_kNN_int', PACKAGE = 'clustertree', data, k, type, bucketSize, splitRule, approx)
}

test_ptr <- function() {
    .Call('clustertree_test_ptr', PACKAGE = 'clustertree')
}

