# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mstToHclust <- function(mst) {
    .Call('_clustertree_mstToHclust', PACKAGE = 'clustertree', mst)
}

chooseMetric <- function(metric_name, config) {
    .Call('_clustertree_chooseMetric', PACKAGE = 'clustertree', metric_name, config)
}

primsRSL <- function(r, r_k, n, alpha, type) {
    .Call('_clustertree_primsRSL', PACKAGE = 'clustertree', r, r_k, n, alpha, type)
}

clusterTree_int <- function(x, k, alpha = 1.414213562373095, type = 0L) {
    .Call('_clustertree_clusterTree_int', PACKAGE = 'clustertree', x, k, alpha, type)
}

kd_knn <- function(query_x, tree_ptr, k, priority) {
    .Call('_clustertree_kd_knn', PACKAGE = 'clustertree', query_x, tree_ptr, k, priority)
}

kdtree <- function(x, bkt_size) {
    .Call('_clustertree_kdtree', PACKAGE = 'clustertree', x, bkt_size)
}

dt_kNN_int <- function(q_x, k, bucketSize, splitRule, metric_ptr, r_x = matrix()) {
    .Call('_clustertree_dt_kNN_int', PACKAGE = 'clustertree', q_x, k, bucketSize, splitRule, metric_ptr, r_x)
}

kNN_int <- function(data, k, type, bucketSize, splitRule, approx) {
    .Call('_clustertree_kNN_int', PACKAGE = 'clustertree', data, k, type, bucketSize, splitRule, approx)
}

kruskalsMST <- function(dist_x) {
    .Call('_clustertree_kruskalsMST', PACKAGE = 'clustertree', dist_x)
}

primsMST <- function(dist_x) {
    .Call('_clustertree_primsMST', PACKAGE = 'clustertree', dist_x)
}

dtb <- function(x, metric_type, bkt_size = 30L, prune = TRUE) {
    .Call('_clustertree_dtb', PACKAGE = 'clustertree', x, metric_type, bkt_size, prune)
}

cut_simplified_hclust <- function(hcl, cl_in, big_n) {
    .Call('_clustertree_cut_simplified_hclust', PACKAGE = 'clustertree', hcl, cl_in, big_n)
}

simplified_hclust <- function(hcl, min_sz) {
    .Call('_clustertree_simplified_hclust', PACKAGE = 'clustertree', hcl, min_sz)
}

vol_nSphere <- function(n, R = 1) {
    .Call('_clustertree_vol_nSphere', PACKAGE = 'clustertree', n, R)
}

